#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/s/code/Work/ ~/s/code/8gears ~/s/code/ ~/s/code/pp/ ~/s/code/OSS/ ~/s/code/learn/ ~/s/code/Freelance/ ~/ ~/s/code/OSS/harborWT/ ~/s/code/OSS/harborSatellite/ ~/s/code/OSS/Harbr/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
