set -g status-style "bg=#0e1415,fg=#eef2f8"
set -g status-left-style "bg=#0e1415,fg=#eef2f8"
set -g status-right-style "bg=#0e1415,fg=#eef2f8"
set -g window-status-style "bg=#0e1415,fg=#c5c6d0"
set -g window-status-current-style "bg=#016AB4,fg=#121318,bold"
set -g pane-border-style "fg=#1a2121"
set -g pane-active-border-style "fg=#016AB4"
set -g message-style "bg=#016AB4,fg=#121318"
set -g message-command-style "bg=#0e1415,fg=#016AB4"
set -g display-panes-colour "#1a2121"
set -g display-panes-active-colour "#016AB4"
