modmap:
  - name: main remaps
    remap:
      # change tab to ctrl
      Ctrl_L: Tab
      # change tab to backspace
      Tab: BackSpace
      # unusable keys
      BackSpace: KEY_RESERVED
      KEY_PAGEDOWN: KEY_RESERVED
      KEY_PAGEUP: KEY_RESERVED
      KEY_SCROLLLOCK: KEY_RESERVED
      KEY_PAUSE: KEY_RESERVED
      KEY_PRINT: KEY_RESERVED
      KEY_INSERT: KEY_RESERVED

      KEY_HOME: KEY_PAGEUP
      KEY_END: KEY_PAGEDOWN
      CapsLock:
        held: leftctrl
        alone: esc
        alone_timeout_millis: 150

keymap:
  - name: new enter
    remap:
      Ctrl-g: enter
