-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        gaps_in = 8,
    },
})

-- Monitors
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "80x-710",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@60.06Hz",
    position = "80x370",
    scale = 1,
    cm = "srgb",
})
